### ISSUE TITLE
[UI] Improve the user interface of about page

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#10]
Improve the user interface as you see fit. Thank you.

**Comment by Sky-De** [comment]
Assign this to me
Thanks

**Comment by dotexe3301** [comment]
i visited the page, but it says **no data available**, btw I know HTML CSS too, see if I can help you!

**Comment by naduncalcey** [comment]
@Sky-De Better to get a pull request before. I have added couple of changes to the project. No data available is an place holder incase there is no data to show. this will prevent User from getting confusing.

**Comment by naduncalcey** [comment]
Hi @Sky-De your PR breaks the production code. UI changes look lit❤️ Can you please take a look into the issue with the PR?

**Comment by naduncalcey** [comment]
@Sky-De all is well. Prod is now working
