### ISSUE TITLE
[enhancement] - Adding a beautiful home page.

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#11]
I have thought about this for a while and this application needs an Home Page that describes what this website do. I'm planning to do this but feel free to start with you own initiative. This project is open-source so anyone can contribute. There is no clear cut design but If you like to show your UI designs through this feel free to do that.

**Comment by Sky-De** [comment]
Assign this to me 
I will handle that in couple of days
Thanks
