### ISSUE TITLE
Need to improve performance and the UI

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#2]
I have added this issue in case anyone want to collaborate with me on this project. I have built the initial features with ReactJS and anyone who like to improve it feel free to reply to this issue. You don't need experience just one line of code is enough to make a change. Feel free to fork and when you finishes your changes just create a pull request an assign me as the reviewer. This is an open source project. Anyone is welcome. 🚀

**Comment by Sky-De** [comment]
@naduncalcey assign this to me
I will take a look at your code and styles and improve them if there was any needs

**Comment by naduncalcey** [comment]
@Sky-De sure you can improve it any way you like. Thanks for your time. I have assigned you the issue so you can work on it.

**Comment by naduncalcey** [comment]
@Sky-De Thanks for the changes.

**Comment by Sky-De** [comment]
Your welcome
I didn't see your last message before pull request
Close this issue
And open new one for refactor structure of app
And i think be good practice if you add another one also for pagination

**Comment by Sky-De** [comment]
@naduncalcey hi again, as it issue is fixed and merged please close this issue as done
Thanks

**Comment by naduncalcey** [comment]
@Sky-De Two new issues are there. If you want to take a look please feel free to fix them as well. Thanks for your awsome work. Happy coding 🫡
