### ISSUE TITLE
[Improvement] - Home page improvement

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#21]
Need to build a good looking home page and anyone who's looking to contribute is welcome. Project already have a landing page and we are looking to improve it.

Technologies preferred:

- SCSS or tailwind CSS
- Three Js

**Comment by shubhjhawar** [comment]
hey @naduncalcey , saw your reply and came here
I wanna take the task, I know tailwindCSS
you have a design in your mind?

**Comment by anubhav1206** [comment]
Can @shubhjhawar and I both be assigned to work on this?

**Comment by naduncalcey** [comment]
@anubhav1206 @shubhjhawar I have assigned you both to this task. I have no design in mind yet. you guys have the freedom to do your own work and we have planning to go with a dark theme. please refer to contributors page. Current style code is not good due to fast paced development. Thank you. Feel free to do your own design if you prefer.
