### ISSUE TITLE
[UI-Issue] - Pokemon type text is wrong. it should be poppins font.

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#22]
<img width="295" alt="Screenshot 2023-09-04 at 11 54 31" src="https://github.com/naduncalcey/pokemon-tcg-app/assets/110454669/2ca1cecf-c895-47f2-89b6-3df2fc1f9d1d">
 Above screen shot shows the issue. look at the "Fire" text.

This issue is created so an beginner can do his first PR to an open source project.

**Comment by naduncalcey** [comment]
https://github.com/naduncalcey/pokemon-tcg-app/pull/23/commits/2ebceebebde31cebaf354a4d10cb518b388c2fc9

**Comment by tnrnz** [comment]
fixed

**Comment by naduncalcey** [comment]
@tnrnz please add a star if you like the project🚀
