### ISSUE TITLE
[Improvement] - Home page UI enhancement

### ISSUE THREAD

**Issue by shubhjhawar** [naduncalcey/pokemon-tcg-app#28]
@naduncalcey i know you closed this issue, but I feel like there is still some work to be done. Ill go ahead and work on it, try to make it even better.

**Comment by shubhjhawar** [comment]
<img width="960" alt="image" src="https://github.com/naduncalcey/pokemon-tcg-app/assets/67875612/ba32f2ff-86b3-43a7-8e0b-d29fa4724066">
<img width="960" alt="image" src="https://github.com/naduncalcey/pokemon-tcg-app/assets/67875612/2b11cc50-760a-4dae-a592-df260f1a480b">
I changed the format a little, then added some gradients and instead of just charizard, it shows random pokemons every 3 seconds

**Comment by naduncalcey** [comment]
@shubhjhawar first home screen with the image looks awesome 🚀. Yes please make your PR I'll merge this right away. UI looks good. Please check the responsive UI if your planning to make the UI responsive.

**Comment by shubhjhawar** [comment]
<img width="960" alt="image" src="https://github.com/naduncalcey/pokemon-tcg-app/assets/67875612/9d5724cc-22fb-40ed-9f70-82531a86163e">
in smaller screens the 2 divs come one after the other (for responsive UI)
I will raise the PR in a moment

**Comment by shubhjhawar** [comment]
https://github.com/naduncalcey/pokemon-tcg-app/pull/29

**Comment by shubhjhawar** [comment]
This issue is related to the pull request: https://github.com/naduncalcey/pokemon-tcg-app/pull/29

**Comment by naduncalcey** [comment]
Changes merged.

**Comment by naduncalcey** [comment]
@shubhjhawar please add a star to the project if you like it. Thank you.

**Comment by shubhjhawar** [comment]
i will star it right away. 
Please give me more work, thanks @naduncalcey
