### ISSUE TITLE
[Bug] - Set search card UI is different from the Card Search card UI

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#5]
Expected Outcome: The card view UI should be consistent.

Problem Location: [view problem](https://pokemon-tcg-v1.netlify.app/set-search)

**Comment by Sky-De** [comment]
@naduncalcey hi again
Assigned this to me
I will fix that too

**Comment by naduncalcey** [comment]
assigned🚀 @Sky-De
