### ISSUE TITLE
[enhancement] - adding pagination to the card layout

### ISSUE THREAD

**Issue by naduncalcey** [naduncalcey/pokemon-tcg-app#7]
This ticket is to improve the UX of the card layout. Add a pagination controls to 15 cards per screen. (This total can be decided by the developer. always prioritise 1080p desktop.)

**Comment by Vayras** [comment]
Hi, @naduncalcey I would like to work on this, Please assign this to me

**Comment by Vayras** [comment]
@naduncalcey I have created a pull request regarding this issue which adds the pagination , let me know if there are any issues with the code

**Comment by naduncalcey** [comment]
@Vayras Looks good! Happy Coding🫡
PR: https://github.com/naduncalcey/pokemon-tcg-app/pull/8
